import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Article from 'components/article'
import { getAllList } from '@/api'

interface Prop {
  list: any
}

export default function Home({ list }: Prop) {
  return (
    <>
      <Head>
        <title>i21y</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/i21y.ico"
        />
      </Head>
      <main className={styles.main}>
        {list.map((item: any) => (
          <Article data={item}></Article>
        ))}
      </main>
    </>
  )
}

export async function getStaticProps() {
  const list = getAllList()
  return {
    props: {
      list: list
    },
    revalidate: 14400
  }
}
