/*
 * @Author: Jerrvis Jerrvis@outlook.com
 * @Date: 2023-03-05 15:01:54
 * @LastEditors: Jerrvis Jerrvis@outlook.com
 * @LastEditTime: 2023-03-05 15:43:34
 * @FilePath: \nextjs-blog\pages\index.tsx
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 */
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Article from "components/article";
import { getAllList } from "@/api";

const inter = Inter({ subsets: ["latin"] });

interface Prop {
  list: any;
}

export default function Home({ list }: Prop) {
  return (
    <>
      <Head>
        <title>i21y</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/i21y.ico" />
      </Head>
      <main className={styles.main}>
        {list.map((item: any) => (
          <Article data={item}></Article>
        ))}
      </main>
    </>
  );
}

export async function getStaticProps() {
  const list = getAllList();
  return {
    props: {
      list: list,
    },
    revalidate: 43200,
  };
}
